target("kernel")
    set_kind("binary")
    set_arch("x86_64")
    add_files("core/*.c")
    add_files("core/*.asm", {force = {nasm = true}})
    add_values("nasm.flags", "-felf64")
    set_filename("kernel")
    add_ldflags("-T$(projectdir)/meta/linker.ld", { force = true })

    add_deps("limine")
    add_deps("ssfn")
    add_deps("logger")

    -- Debug configuration (always on for now)
    add_cxflags("-g")
    add_cxflags("-O0")
    add_ldflags("-g", { force = true })

    -- Generate debug symbols
    after_build(function (target)
        import("core.project.config")
        local targetfile = target:targetfile()
        print("Target file: " .. targetfile)
        os.execv("llvm-objcopy", {"--only-keep-debug", targetfile, targetfile .. ".sym"})
        os.execv("llvm-objcopy", {"--strip-debug", targetfile})
        os.execv("llvm-objcopy", {"--add-gnu-debuglink=" .. targetfile .. ".sym", targetfile})
    end)
