target("jemi")
    set_kind("static")
    add_files("src/*.c")
    add_includedirs("$(projectdir)/src/libs/printf")
    add_includedirs("$(projectdir)/src/libs/libk")
    add_includedirs("include", {public = true})
    add_defines("JEMI_BUILD", {public = true})
    add_deps("printf")
    add_deps("libk")
