target("hello")
    set_kind("binary")
    add_files("hello.c")
    add_cflags("-ffreestanding", "-fno-stack-protector", "-fno-pic", "-mno-red-zone", "-m64")
    add_cxflags("-nostdlib")
    set_arch("x86_64")
    add_cxflags("-fno-builtin")
    add_cxflags("-mstack-alignment=16")
    add_cxflags("-fomit-frame-pointer")
    add_cxflags("-Os")
    add_ldflags("-e _init", { force = true })
    add_ldflags("-no-pie", { force = true })
