name: clang-format Check
on: [pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "src/kernel"
          - "src/hal"
          - "src/libs/libk"
          - "src/libs/logger"
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: "13"
          check-path: ${{ matrix.path }}
